@ECHO OFF
Color 80
REM This file was generated by 'PyProgramWorkbook'  
REM
REM It updates/installs all required libraries for the MobaLedLib projects.
REM
REM Attention:
REM This program must be started from the arduino libraries directory
REM

CHCP 65001 >NUL

ECHO **********************
ECHO Updating MobaLedLib...
ECHO **********************
if EXIST MobaLedLib\NUL (
   ECHO deleting old directory MobaLedLib\
   rmdir MobaLedLib\ /s /q
   REM timeout /T 3 /nobreak
)
if EXIST MobaLedLib\NUL (
   ECHO Error deleting old directory MobaLedLib\
   ECHO For some reasons the directory could not be deleted ;-(
   ECHO Check if an other program is active which prevents the deleting
   ECHO of the directory
   ECHO.
   ECHO Going to try a second time
   PAUSE
   rmdir MobaLedLib\ /s /q
   timeout /T 3 /nobreak
)
if EXIST MobaLedLib\NUL (
   COLOR 4F
   ECHO Error: Still not able to delete the old directory MobaLedLib\   ;-(((
   PAUSE
)
powershell Invoke-WebRequest "https://github.com/Hardi-St/MobaLedLib/archive/master.zip" -o:MobaLedLib.zip
ECHO Invoke-WebRequest result: %ERRORLEVEL%
IF ERRORLEVEL 1 Goto ErrorMsg
ECHO.

Exit

:ErrorMsg
   COLOR 4F
   ECHO   ****************************************
   ECHO    Da ist was schief gegangen ;-(
   ECHO   ****************************************
   Pause
