@ECHO OFF
Color 80
REM This file was generated by 'PyProgramWorkbook'  
REM
REM It updates/installs all required libraries for the MobaLedLib projects.
REM
REM Attention:
REM This program must be started from the arduino libraries directory
REM

CHCP 65001 >NUL
Exit

:ErrorMsg
   COLOR 4F
   ECHO   ****************************************
   ECHO    Da ist was schief gegangen ;-(
   ECHO   ****************************************
   Pause
