VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Tabelle5"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Option Explicit

'-------------------------------
Private Sub Start_Button_Click()
'-------------------------------
  Arduino_Button_StartPage
End Sub

'-------------------------------
Private Sub Worksheet_Activate()
'-------------------------------
  Global_Worksheet_Activate
End Sub

